lib/ra10ke.rb

This has been tested to not cause issues with earlier r10k versions either.

Update ra10ke with r10k 2.4.0 support

---

.gitignore
README.md
lib/ra10ke.rb
ra10ke.gemspec

Unfortunately utilizing the forge is not always an option, either due to the forge being out of sync with code out on github, or security requirements not permitting the releasing of internal code into the public sphere.
As such it is quite common to have an extensive deployment of private code spanning multiple puppet environments internally. As such this change allows for querying refs via git ls-remote and attempting to resolve out of date status. Authentication if needed is done via environmental variables (such as ssh keys or git global config). 
When a module is pinned to an SHA ref HEAD on the remote repository is compared to determine outdated status.
Special note on tags... I could not figure out a less opinionated way to evaluate tagging other than to only function if the tag …

Added git support

---

README.md
lib/ra10ke.rb
lib/ra10ke/solve.rb
ra10ke.gemspec

I implemented a dependency solver for Puppetfiles that's rather much faster than Librarian at least as far as I can tell. The limiting factor is how slowly the Forge API returns release metadata.
I've tested, and it works for me at least. I'm now looking for feedback on what the task should actually do (I kind of want it to output an updated Puppetfile, but it's useful enough as is). It supports both git and Forge modules
The solver uses YAML::Store to cache release metadata, so subsequent
runs will be somewhat faster, but it still only fetches the three most recent releases for each dependency.

Add a dependency solver based on the Ruby Solve library

---

lib/ra10ke.rb

Also add a better output when tags don't match supported naming convention

Add numeric tag convention support

---

lib/ra10ke.rb

Use the exposed helper aptly called `version` instead of trying to deal with the messy `desired_ref` which can sometimes be set as `:control_branch` especially for people with newer Puppetfiles and crazy branching strategies.
See #10.

Avoid using `desired_ref` directly for Git

---

ra10ke.gemspec

As we use `solve` and it [requires Ruby `>= 2.1.0`](https://github.com/berkshelf/solve/blob/e53a2305bb7ff5ef161dc5181a401b45d425ace6/solve.gemspec#L17), we can be explicit in our Gem Spec as well.
See #9.

Set required Ruby version as `>= 2.1.0`

---

lib/ra10ke.rb

some modules have weird tags.
e.g.
puppetlabs-git
```
git ls-remote https://github.com/puppetlabs/puppetlabs-git.git | tail -3
cfbf74dbb370f00d1349d8589ba0d963d5d503eb	refs/tags/0.4.0^{}
a0cf10a8cec8728abb008fdd778e243e84dde62c	refs/tags/0.5.0
f7e4ff5cc0b8e887ff07579bb383ce9e173fb93c	refs/tags/0.5.0^{}
```
ra10ke reports this as outdated:
git is OUTDATED: 0.5.0 vs 0.5.0^{}
This fix ensures that we only use correct version tags

ignore invalid ref

---

lib/ra10ke.rb
ra10ke.gemspec

Following the quick notes in f20ba1267962a9b23f22346550f61c56886206da here is a proposal for dealing with Git tags without using regular expressions - use [Semantic Versioning](https://semver.org/spec/v2.0.0.html) instead.
This PR removes support for `X` and `X.Y` version tags, but supports `vX.Y.Z` along with `X.Y.Z` and full SemVer tags such as `v2.3.1-rc.2+20180405`. If there is a reason to add support for the `X` and `X.Y` formats, those can be squeezed in.

Use Semantic Versioning for Git tags

---

lib/ra10ke.rb

This follows up #16.
```
'11.2.3' != '1.2.3'
'v1.2.3' == '1.2.3'
```

Be careful around trimming Git tags

---

lib/ra10ke.rb
lib/ra10ke/solve.rb

Ensure Puppetfile gets parsed with absolute path

---

README.md
lib/ra10ke.rb

Add a simple r10k:install task that can install modules listed in the
provided Puppetfile.
Task requires an argument that can be provided by calling the task as
follows:
rake r10k:install[path]
Fixes: #2

Add rudimentary r10k:install task

---

README.md
lib/ra10ke.rb
lib/ra10ke/solve.rb

This is intended as a discussion more than an actually finished PR.
When I tried to use this gem in our Rakefile I immediately had the problem that our directories are not the defaults, but it would be convenient if the rake tasks where configured in the Rakefile so they are by default doing the right thing.
The idea is to configure the locations of the Puppetfile, modules path etc. similar to how you would configure settings of your rspec rake tasks.
The provided PR makes it possible to configure the tasks in the Rakefile with:
```
Ra10ke::RakeTask.new do |t|
t.basedir = File.join(Dir.pwd, 'my_custom/modules/path')
t.force = true                                  
end
```
What do you think?

Make it possible to configure the tasks in the rakefile

---

README.md
lib/ra10ke.rb
lib/ra10ke/dependencies.rb
lib/ra10ke/install.rb
lib/ra10ke/syntax.rb

There are actually three different things here:
- The tasks got separated into their own modules similar to how solve already was
- Added a purge option to the install task
- Fix the handling of version tags with a leading "v"
Let me know if I should separate them. I had to put them together in the same PR because the move of the taks to the modules would have resulted in conflicts for the purge changes.

Refactor tasks

---

lib/ra10ke/puppetfile_parser.rb
spec/fixtures/Puppetfile
spec/ra10ke/puppetfile_parser_spec.rb

If a module's Git URL contains the word 'mod', then it's split at that point and handled as two modules, this causes the `rake r10k:validate` task to fail quite spectacularly - among other things.

Fix a fault in the mod handling behaviour

---

lib/ra10ke/validate.rb

I just realized - while digging through the code for unrelated reasons - that I accidentally ruined the documentation for the `#all_refs` method when fixing the lost ref bug.  
This PR restores the documentation to a correct state again, so I don't have to feel bad about it anymore.

Fix the faulty docs for Ra10ke::Validate#all_refs after #42

---

.gitignore
ra10ke.gemspec
spec/spec_helper.rb

* previously there was not a way to produce coverage reports.
This adds the simplecov gem and allows you to enable coverage
by setting COVERAGE=true environment variable when running tests.
Reports are available under coverage directory when run.

Add coverage reports

---

lib/ra10ke/git_repo.rb
lib/ra10ke/validate.rb
spec/fixtures/Puppetfile_with_control_branch
spec/ra10ke/validate_spec.rb

This will - when running into a module with control_branch - attempt to
get the correct branch first from the environment variable CONTROL_BRANCH,
followed by the current git repo branch, then the environment variable
CONTROL_BRANCH_FALLBACK, and finally failing over to assume it to be 'main'
Fixes #58

Support r10k:validate with control_branch modules

---

lib/ra10ke/validate.rb
spec/fixtures/Puppetfile_with_control_branch
spec/ra10ke/validate_spec.rb

Noticed that I'd missed these keys when I was writing the code, so a late PR that adds an example and tests.
This PR then also handles `default_branch` and `default_branch_override` when dealing with :control_branch, based on how `R10K::Module::Git` does the lookup
The resulting flow for figuring out the correct branch will then be; `$CONTROL_BRANCH` > current branch > `:default_branch_override` > `$CONTROL_BRANCH_FALLBACK` > `:default_branch` > `'main'`

Add handling for additional r10k args in validate for control_branch

---

README.md
lib/ra10ke.rb
lib/ra10ke/deprecation.rb
lib/ra10ke/puppetfile_parser.rb
spec/fixtures/Puppetfile
spec/ra10ke/deprecation_spec.rb
spec/ra10ke/puppetfile_parser_spec.rb

A task that checks for deprecated Forge modules
When writing this I noticed that the parser does something interesting on modules where the namespace and name are the same, so I added a test for that as well. Should probably be fixed, but I didn't want to do it as part of this feature.

Add r10k:deprecation task

---

lib/ra10ke/solve.rb

* Previously if the directory did not exist the rake task would fail
This will create the necessary directory before using it which
fixes the problem.

Fix #70 - cache dir does not exist

---

lib/ra10ke/dependencies.rb
ra10ke.gemspec
spec/ra10ke/dependencies_spec.rb

Takes the boring old output and converts it to a nice table.
From this:
```
puppetlabs-reboot is OUTDATED: 1.2.1 vs 4.1.0
puppetlabs-registry is OUTDATED: 1.1.4 vs 4.0.1
puppetlabs-powershell is OUTDATED: 2.1.0 vs 5.0.0
puppetlabs-acl is OUTDATED: 1.1.2 vs 4.0.0
puppetlabs-wsus_client is OUTDATED: 1.0.3 vs 4.0.0
```
to 
```
NAME               | INSTALLED | LATEST   | TYPE  | MESSAGE 
-------------------|-----------|----------|-------|---------
choria-choria      | 0.26.2    | 0.27.1   | forge | outdated
puppetlabs-inifile | 2.2.0     | 5.2.0    | forge | outdated
puppetlabs-stdlib  | 4.24.0    | 8.1.0    | forge | outdated
puppetlabs-concat  | 4.0.0     | 7.1.1    | forge | outdated
puppetlabs-ntp     | 6.4.1     | 9.1.0    | forge | outdated
puppet-archive     | 3.1.1     | 6.0.2    | …
```

Dependencies Table output 

---

.github/workflows/test.yml
ra10ke.gemspec

We already have one backwards-incompatible change merges so we could use this to also cleanup the ruby versions. 2.4, 2.5 and 2.6 are EoL:
https://www.ruby-lang.org/en/downloads/branches/

Bump minimal Ruby Version 2.4.0->2.7.0

---

README.md
lib/ra10ke.rb
lib/ra10ke/dependencies.rb
lib/ra10ke/git_repo.rb
spec/fixtures/Puppetfile_git_conversion
spec/ra10ke/dependencies_spec.rb
spec/ra10ke/git_repo_spec.rb

* This feature is useful when you want to bring all the forge modules
in house on the local git server.  This will auto lookup
the module's homepage url and use that as the git source.
Sometimes the author doesn't provide the homepage url so this
will fail and the code isn't always tagged to the version so
some manual intervention will be required before final approval
of conversion output.
Example: `bundle exec rake r10k:print_git_conversion`
Converts the following
```ruby
mod 'puppetlabs/reboot'
mod 'puppetlabs/registry',                 '1.1.4'
mod 'puppetlabs/powershell',               '2.1.0'
mod 'puppetlabs/acl',                      '1.1.2'
mod 'puppetlabs/wsus_client',              '1.0.3'
mod 'puppetlabs/chocolatey',               '3.0.0'
mod 'puppet/download_file', …
```

Converts puppet forge module entries into puppetfile git entries

---

lib/ra10ke/dependencies.rb

Currently the dependency check does not return an exit code, for ci pipelines it's very helpful if it would return an exit code

Add exit codes to dependency check

---

Rakefile

We included rake tasks to build the gem, but out pipeline doesn't use it. We always build with `gem build`.

Cleanup Rakefile; remove unused rake tasks

---

.github/workflows/test.yml
.rubocop.yml
ra10ke.gemspec

This allows us to use the latest version of puppet_forge client.

Require Ruby 3.1 & puppet_forge 6 & r10k 5

---

lib/ra10ke/dependencies.rb

With this, ra10ke will no longer generate false positives and excessive log spam on versions of the R10k gem >= 3.10.0
It also improves performance and removes unnecessary load by completely skipping version checks for modules using control branch, since that will always be a no-op anyway, and the check would cause each repo to be pulled twice just to do said no-op. (First by R10k's cache verifying that the branch exists, then followed by ra10ke's `Git.ls_remote` call to check that it really _is_ a branch)
As it turns out, the threaded checking caused git to run into the subshell limit on our r10k repo if the repository host was slow to respond.

Improve dependencies check against :control_branch
